#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# --- Modern Tooling ----------------------------------------------
alias cat='bat'

# --- Directory listings via eza ----------------------------------------------
alias la='eza -la --icons'
alias lt='eza --tree --level=2 --icons'
ls() { command eza --icons "$@"; }
ll() { command eza -l --icons "$@"; }

# --- Interactive Tooling ----------------------------------------------
alias grep='grep --color=auto'
alias thumbnails='nsxiv -t'

PS1='[\u@\h \W]\$ '

export PATH="$PATH:$HOME/.local/bin"

# Make man pages more readable
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

# Zoxide
eval "$(zoxide init bash)"

# Mise
eval "$($HOME/.local/bin/mise activate bash)"

# Starship
eval "$(starship init bash)"
