[Greeter]
background=/usr/share/backgrounds/macos-sequoia.jpg
draw-user-backgrounds=false
font-name=JetBrains Mono 11
clock-format=%H:%M
cursor-theme-name=phinger-cursors-light
cursor-theme-size=24
show-a11y=false
show-keyboard=false
