# BEGIN_KITTY_THEME
# Gruvbox Material Dark Medium
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KITTY_CURSOR
# Enables the trail, and triggers it when the cursor stays in one spot for at least 200 ms
cursor_trail 200
# Controls how quickly the trail fades (from fastest to slowest decay)
cursor_trail_decay 0.1 0.4
# Prevents the trail from showing when the cursor only moves a small distance (fewer than 2 cells)
cursor_trail_start_threshold 2
# END_KITTY_CURSOR

# BEGIN_KITTY_MISC
enable_audio_bell no
# END_KITTY_MISC
